name: prediction_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^26.1.35 # Professional Grade Charts
  google_fonts: ^5.1.0                # Modern Typography
  http: ^1.1.0
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
